/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AnagraficaCittadino } from '../model/anagraficaCittadino';
import { CondizioneFamiliare } from '../model/condizioneFamiliare';
import { CondizioneOccupazionale } from '../model/condizioneOccupazionale';
import { Errore } from '../model/errore';
import { SvantaggioAbitativo } from '../model/svantaggioAbitativo';
import { TitoloDiStudio } from '../model/titoloDiStudio';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class AnagraficheService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * torna l&#x27;anagrafica del cittadino passando come parametro l&#x27;id
     * torna l&#x27;anagrafica del cittadino passando come parametro l&#x27;id
     * @param idAnagraficaCittadino codice della provincia a cercare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAnafraficaCittadinoPerId(idAnagraficaCittadino: number, observe?: 'body', reportProgress?: boolean): Observable<AnagraficaCittadino>;
    public getAnafraficaCittadinoPerId(idAnagraficaCittadino: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AnagraficaCittadino>>;
    public getAnafraficaCittadinoPerId(idAnagraficaCittadino: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AnagraficaCittadino>>;
    public getAnafraficaCittadinoPerId(idAnagraficaCittadino: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idAnagraficaCittadino === null || idAnagraficaCittadino === undefined) {
            throw new Error('Required parameter idAnagraficaCittadino was null or undefined when calling getAnafraficaCittadinoPerId.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idAnagraficaCittadino !== undefined && idAnagraficaCittadino !== null) {
            queryParameters = queryParameters.set('idAnagraficaCittadino', <any>idAnagraficaCittadino);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<AnagraficaCittadino>('get',`${this.basePath}/anagrafiche/anagrafica`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * torna l&#x27;anagrafica del cittadino secondo i campi SPID
     * torna l&#x27;anagrafica del cittadino ricavata dalle header SPID
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAnagraficaCittadinoSpid(observe?: 'body', reportProgress?: boolean): Observable<AnagraficaCittadino>;
    public getAnagraficaCittadinoSpid(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AnagraficaCittadino>>;
    public getAnagraficaCittadinoSpid(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AnagraficaCittadino>>;
    public getAnagraficaCittadinoSpid(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<AnagraficaCittadino>('get',`${this.basePath}/anagrafiche/anagrafica-suggest`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco condizione-occupazionale
     * torna l&#x27;elenco delle condizione occupazionale
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCondizioneOccupazionale(observe?: 'body', reportProgress?: boolean): Observable<Array<CondizioneOccupazionale>>;
    public getCondizioneOccupazionale(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CondizioneOccupazionale>>>;
    public getCondizioneOccupazionale(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CondizioneOccupazionale>>>;
    public getCondizioneOccupazionale(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CondizioneOccupazionale>>('get',`${this.basePath}/anagrafiche/condizione-occupazionale`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco condizioni familiari
     * elenco condizoni familiari
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCondizioniFamiliare(observe?: 'body', reportProgress?: boolean): Observable<Array<CondizioneFamiliare>>;
    public getCondizioniFamiliare(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CondizioneFamiliare>>>;
    public getCondizioniFamiliare(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CondizioneFamiliare>>>;
    public getCondizioniFamiliare(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<CondizioneFamiliare>>('get',`${this.basePath}/anagrafiche/condizione-familiare`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco svantaggi-abitativo
     * elenco svantaggi abitativo
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSvantaggiAbitativo(observe?: 'body', reportProgress?: boolean): Observable<Array<SvantaggioAbitativo>>;
    public getSvantaggiAbitativo(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SvantaggioAbitativo>>>;
    public getSvantaggiAbitativo(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SvantaggioAbitativo>>>;
    public getSvantaggiAbitativo(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<SvantaggioAbitativo>>('get',`${this.basePath}/anagrafiche/svantaggi-abitativo`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco titolo-studio
     * torna l&#x27;elenco dei titolo di studio
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTitoliStudio(observe?: 'body', reportProgress?: boolean): Observable<Array<TitoloDiStudio>>;
    public getTitoliStudio(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<TitoloDiStudio>>>;
    public getTitoliStudio(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<TitoloDiStudio>>>;
    public getTitoliStudio(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<TitoloDiStudio>>('get',`${this.basePath}/anagrafiche/titolo-studio`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce un&#x27;anagradica cittadino
     * inserisce un&#x27;anagradica cittadino
     * @param body anagrafica cittadino a inserire
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertAnagraficaCittadino(body?: AnagraficaCittadino, observe?: 'body', reportProgress?: boolean): Observable<AnagraficaCittadino>;
    public insertAnagraficaCittadino(body?: AnagraficaCittadino, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AnagraficaCittadino>>;
    public insertAnagraficaCittadino(body?: AnagraficaCittadino, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AnagraficaCittadino>>;
    public insertAnagraficaCittadino(body?: AnagraficaCittadino, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<AnagraficaCittadino>('post',`${this.basePath}/anagrafiche/anagrafica`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * modifica un&#x27;anagradica cittadino
     * modifica un&#x27;anagradica cittadino
     * @param body anagrafica cittadino a modificare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateAnagraficaCittadino(body?: AnagraficaCittadino, observe?: 'body', reportProgress?: boolean): Observable<AnagraficaCittadino>;
    public updateAnagraficaCittadino(body?: AnagraficaCittadino, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AnagraficaCittadino>>;
    public updateAnagraficaCittadino(body?: AnagraficaCittadino, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AnagraficaCittadino>>;
    public updateAnagraficaCittadino(body?: AnagraficaCittadino, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<AnagraficaCittadino>('put',`${this.basePath}/anagrafiche/anagrafica`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
