/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { AnagraficaCittadinoRicerca } from '../model/anagraficaCittadinoRicerca';
import { Cittadino } from '../model/cittadino';
import { DashboardCittadino } from '../model/dashboardCittadino';
import { Errore } from '../model/errore';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class CittadiniService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * elenco cittadini associati a una idea d&#x27;impresa
     * elenco svantaggi abitativo
     * @param idIdeaDiImpresa codice della provincia a cercare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCittadinoPerIdeaImpresa(idIdeaDiImpresa: number, observe?: 'body', reportProgress?: boolean): Observable<Cittadino>;
    public getCittadinoPerIdeaImpresa(idIdeaDiImpresa: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Cittadino>>;
    public getCittadinoPerIdeaImpresa(idIdeaDiImpresa: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Cittadino>>;
    public getCittadinoPerIdeaImpresa(idIdeaDiImpresa: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idIdeaDiImpresa === null || idIdeaDiImpresa === undefined) {
            throw new Error('Required parameter idIdeaDiImpresa was null or undefined when calling getCittadinoPerIdeaImpresa.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idIdeaDiImpresa !== undefined && idIdeaDiImpresa !== null) {
            queryParameters = queryParameters.set('idIdeaDiImpresa', <any>idIdeaDiImpresa);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Cittadino>('get',`${this.basePath}/cittadini/cittadino-idea-impresa`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * ricerca cittadini per parametri
     * elenco di cittadini pasando diversi parametri di ricerca
     * @param nome nome cittadino
     * @param cognome cognome cittadino
     * @param email email cittadino
     * @param codiceFiscale codice fiscale cittadino
     * @param codAreaTerritoriale codice area territoriale
     * @param dataInseritoDa data minima per la ricerca
     * @param dataInseritoA data massima per la ricerca
     * @param idOperatore id operatore
     * @param idSoggettoAttuatore id soggetto attuatore
     * @param pageIndex 
     * @param pageSize 
     * @param orderBy 
     * @param sortDirection 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCittadinoPerParametri(nome?: string, cognome?: string, email?: string, codiceFiscale?: string, codAreaTerritoriale?: string, dataInseritoDa?: string, dataInseritoA?: string, idOperatore?: number, idSoggettoAttuatore?: number, pageIndex?: number, pageSize?: number, orderBy?: string, sortDirection?: string, observe?: 'body', reportProgress?: boolean): Observable<AnagraficaCittadinoRicerca>;
    public getCittadinoPerParametri(nome?: string, cognome?: string, email?: string, codiceFiscale?: string, codAreaTerritoriale?: string, dataInseritoDa?: string, dataInseritoA?: string, idOperatore?: number, idSoggettoAttuatore?: number, pageIndex?: number, pageSize?: number, orderBy?: string, sortDirection?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<AnagraficaCittadinoRicerca>>;
    public getCittadinoPerParametri(nome?: string, cognome?: string, email?: string, codiceFiscale?: string, codAreaTerritoriale?: string, dataInseritoDa?: string, dataInseritoA?: string, idOperatore?: number, idSoggettoAttuatore?: number, pageIndex?: number, pageSize?: number, orderBy?: string, sortDirection?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<AnagraficaCittadinoRicerca>>;
    public getCittadinoPerParametri(nome?: string, cognome?: string, email?: string, codiceFiscale?: string, codAreaTerritoriale?: string, dataInseritoDa?: string, dataInseritoA?: string, idOperatore?: number, idSoggettoAttuatore?: number, pageIndex?: number, pageSize?: number, orderBy?: string, sortDirection?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {














        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (nome !== undefined && nome !== null) {
            queryParameters = queryParameters.set('nome', <any>nome);
        }
        if (cognome !== undefined && cognome !== null) {
            queryParameters = queryParameters.set('cognome', <any>cognome);
        }
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('email', <any>email);
        }
        if (codiceFiscale !== undefined && codiceFiscale !== null) {
            queryParameters = queryParameters.set('codiceFiscale', <any>codiceFiscale);
        }
        if (codAreaTerritoriale !== undefined && codAreaTerritoriale !== null) {
            queryParameters = queryParameters.set('codAreaTerritoriale', <any>codAreaTerritoriale);
        }
        if (dataInseritoDa !== undefined && dataInseritoDa !== null) {
            queryParameters = queryParameters.set('dataInseritoDa', <any>dataInseritoDa);
        }
        if (dataInseritoA !== undefined && dataInseritoA !== null) {
            queryParameters = queryParameters.set('dataInseritoA', <any>dataInseritoA);
        }
        if (idOperatore !== undefined && idOperatore !== null) {
            queryParameters = queryParameters.set('idOperatore', <any>idOperatore);
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }
        if (pageIndex !== undefined && pageIndex !== null) {
            queryParameters = queryParameters.set('pageIndex', <any>pageIndex);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (orderBy !== undefined && orderBy !== null) {
            queryParameters = queryParameters.set('orderBy', <any>orderBy);
        }
        if (sortDirection !== undefined && sortDirection !== null) {
            queryParameters = queryParameters.set('sortDirection', <any>sortDirection);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<AnagraficaCittadinoRicerca>('get',`${this.basePath}/cittadini`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * stato compilazione del cittadino
     * stato compilazione del cittadino
     * @param body dato cittadino
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDashboardCittadino(body?: Cittadino, observe?: 'body', reportProgress?: boolean): Observable<DashboardCittadino>;
    public getDashboardCittadino(body?: Cittadino, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DashboardCittadino>>;
    public getDashboardCittadino(body?: Cittadino, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DashboardCittadino>>;
    public getDashboardCittadino(body?: Cittadino, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DashboardCittadino>('post',`${this.basePath}/cittadini/cittadino/dashboard`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cambia lo stato della idea d&#x27;impresa a concluso e invia la mail di compilazione questionario terza fase
     * 
     * @param body dato cittadino
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateIdeaImpresaConclusa(body?: DashboardCittadino, observe?: 'body', reportProgress?: boolean): Observable<DashboardCittadino>;
    public updateIdeaImpresaConclusa(body?: DashboardCittadino, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DashboardCittadino>>;
    public updateIdeaImpresaConclusa(body?: DashboardCittadino, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DashboardCittadino>>;
    public updateIdeaImpresaConclusa(body?: DashboardCittadino, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DashboardCittadino>('put',`${this.basePath}/cittadini/cittadino/concludi-mip`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * cambia lo stato della idea d&#x27;impresa a inviato e invia la mail di conferma di partecipazione al&#x27;incontro
     * cambia lo stato della idea d&#x27;impresa a inviato e invia la mail di conferma di partecipazione al&#x27;incontro
     * @param body dato cittadino
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateIdeaImpresaInviata(body?: DashboardCittadino, observe?: 'body', reportProgress?: boolean): Observable<DashboardCittadino>;
    public updateIdeaImpresaInviata(body?: DashboardCittadino, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DashboardCittadino>>;
    public updateIdeaImpresaInviata(body?: DashboardCittadino, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DashboardCittadino>>;
    public updateIdeaImpresaInviata(body?: DashboardCittadino, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DashboardCittadino>('put',`${this.basePath}/cittadini/cittadino/invia-dati`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
