/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Cittadinanza } from '../model/cittadinanza';
import { Comune } from '../model/comune';
import { Errore } from '../model/errore';
import { Provincia } from '../model/provincia';
import { StatoEstero } from '../model/statoEstero';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class DatiComuniService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * elenco cittadinanze
     * elenco delle cittadinanze
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCittadinanze(observe?: 'body', reportProgress?: boolean): Observable<Array<Cittadinanza>>;
    public getCittadinanze(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Cittadinanza>>>;
    public getCittadinanze(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Cittadinanza>>>;
    public getCittadinanze(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Cittadinanza>>('get',`${this.basePath}/cittadinanze`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco comuni
     * elenco dei comuni
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getComuni(observe?: 'body', reportProgress?: boolean): Observable<Array<Comune>>;
    public getComuni(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Comune>>>;
    public getComuni(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Comune>>>;
    public getComuni(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Comune>>('get',`${this.basePath}/comuni`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco comuni della provincia
     * elenco delle comuni
     * @param provincia codice della provincia a cercare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getComuniPerProvincia(provincia: string, observe?: 'body', reportProgress?: boolean): Observable<Array<Comune>>;
    public getComuniPerProvincia(provincia: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Comune>>>;
    public getComuniPerProvincia(provincia: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Comune>>>;
    public getComuniPerProvincia(provincia: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (provincia === null || provincia === undefined) {
            throw new Error('Required parameter provincia was null or undefined when calling getComuniPerProvincia.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (provincia !== undefined && provincia !== null) {
            queryParameters = queryParameters.set('provincia', <any>provincia);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Comune>>('get',`${this.basePath}/comuni/provincia`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco province
     * elenco delle province
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProvince(observe?: 'body', reportProgress?: boolean): Observable<Array<Provincia>>;
    public getProvince(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Provincia>>>;
    public getProvince(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Provincia>>>;
    public getProvince(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<Provincia>>('get',`${this.basePath}/province`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco province associate ad una regione
     * elenco delle province
     * @param regione codice della regione a db(per il Piemonte 01)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getProvincePerRegione(regione: string, observe?: 'body', reportProgress?: boolean): Observable<Provincia>;
    public getProvincePerRegione(regione: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Provincia>>;
    public getProvincePerRegione(regione: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Provincia>>;
    public getProvincePerRegione(regione: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (regione === null || regione === undefined) {
            throw new Error('Required parameter regione was null or undefined when calling getProvincePerRegione.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (regione !== undefined && regione !== null) {
            queryParameters = queryParameters.set('regione', <any>regione);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Provincia>('get',`${this.basePath}/province/regione`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco stati esteri
     * elenco degli StatiEsteri
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getStatiEsteri(observe?: 'body', reportProgress?: boolean): Observable<Array<StatoEstero>>;
    public getStatiEsteri(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<StatoEstero>>>;
    public getStatiEsteri(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<StatoEstero>>>;
    public getStatiEsteri(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<StatoEstero>>('get',`${this.basePath}/stati-esteri`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
