/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Errore } from '../model/errore';
import { ReportQuestionario } from '../model/reportQuestionario';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DefaultService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * restituzione domande e risposte questionario fase 1
     * restituisce domande e risposte questionario fase 1
     * @param idFase
     * @param dataDa
     * @param dataA
     * @param idSoggettoAttuatore
     * @param idCodAreaTerritoriale
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDomandeRisposte(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, observe?: 'body', reportProgress?: boolean): Observable<ReportQuestionario>;
    public getDomandeRisposte(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReportQuestionario>>;
    public getDomandeRisposte(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReportQuestionario>>;
    public getDomandeRisposte(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idFase !== undefined && idFase !== null) {
            queryParameters = queryParameters.set('idFase', <any>idFase);
        }
        if (dataDa !== undefined && dataDa !== null) {
            queryParameters = queryParameters.set('dataDa', <any>dataDa.toISOString());
        }
        if (dataA !== undefined && dataA !== null) {
            queryParameters = queryParameters.set('dataA', <any>dataA.toISOString());
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }
        if (idCodAreaTerritoriale !== undefined && idCodAreaTerritoriale !== null) {
            queryParameters = queryParameters.set('idCodAreaTerritoriale', <any>idCodAreaTerritoriale);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ReportQuestionario>('get',`${this.basePath}/reportistica/questionari`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
