/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Documento } from '../model/documento';
import { Errore } from '../model/errore';
import { EventoCalendarioRicerca } from '../model/eventoCalendarioRicerca';
import { FileIcs } from '../model/fileIcs';
import { StoricoCalendario } from '../model/storicoCalendario';
import { TipoDocumento } from '../model/tipoDocumento';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class DocumentiService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * carica un documento
     * carica un documento
     * @param idDocumento 
     * @param nomeDocumento 
     * @param descrizioneDocumento 
     * @param codeTipoDocumento 
     * @param documento 
     * @param idOperatoreInserimento 
     * @param idIdeaDiImpresa 
     * @param codUserInserim 
     * @param dataInserim 
     * @param codUserAggiorn 
     * @param dataAggiorn 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public caricaDocumentoForm(idDocumento?: number, nomeDocumento?: string, descrizioneDocumento?: string, codeTipoDocumento?: string, documento?: Blob, idOperatoreInserimento?: number, idIdeaDiImpresa?: number, codUserInserim?: string, dataInserim?: Date, codUserAggiorn?: string, dataAggiorn?: Date, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public caricaDocumentoForm(idDocumento?: number, nomeDocumento?: string, descrizioneDocumento?: string, codeTipoDocumento?: string, documento?: Blob, idOperatoreInserimento?: number, idIdeaDiImpresa?: number, codUserInserim?: string, dataInserim?: Date, codUserAggiorn?: string, dataAggiorn?: Date, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public caricaDocumentoForm(idDocumento?: number, nomeDocumento?: string, descrizioneDocumento?: string, codeTipoDocumento?: string, documento?: Blob, idOperatoreInserimento?: number, idIdeaDiImpresa?: number, codUserInserim?: string, dataInserim?: Date, codUserAggiorn?: string, dataAggiorn?: Date, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public caricaDocumentoForm(idDocumento?: number, nomeDocumento?: string, descrizioneDocumento?: string, codeTipoDocumento?: string, documento?: Blob, idOperatoreInserimento?: number, idIdeaDiImpresa?: number, codUserInserim?: string, dataInserim?: Date, codUserAggiorn?: string, dataAggiorn?: Date, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {












        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/problem+json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (idDocumento !== undefined) {
            formParams = formParams.append('idDocumento', <any>idDocumento) as any || formParams;
        }
        if (nomeDocumento !== undefined) {
            formParams = formParams.append('nomeDocumento', <any>nomeDocumento) as any || formParams;
        }
        if (descrizioneDocumento !== undefined) {
            formParams = formParams.append('descrizioneDocumento', <any>descrizioneDocumento) as any || formParams;
        }
        if (codeTipoDocumento !== undefined) {
            formParams = formParams.append('codeTipoDocumento', <any>codeTipoDocumento) as any || formParams;
        }
        if (documento !== undefined) {
            formParams = formParams.append('documento', <any>documento) as any || formParams;
        }
        if (idOperatoreInserimento !== undefined) {
            formParams = formParams.append('idOperatoreInserimento', <any>idOperatoreInserimento) as any || formParams;
        }
        if (idIdeaDiImpresa !== undefined) {
            formParams = formParams.append('idIdeaDiImpresa', <any>idIdeaDiImpresa) as any || formParams;
        }
        if (codUserInserim !== undefined) {
            formParams = formParams.append('codUserInserim', <any>codUserInserim) as any || formParams;
        }
        if (dataInserim !== undefined) {
            formParams = formParams.append('dataInserim', <any>dataInserim) as any || formParams;
        }
        if (codUserAggiorn !== undefined) {
            formParams = formParams.append('codUserAggiorn', <any>codUserAggiorn) as any || formParams;
        }
        if (dataAggiorn !== undefined) {
            formParams = formParams.append('dataAggiorn', <any>dataAggiorn) as any || formParams;
        }

        return this.httpClient.request<any>('post',`${this.basePath}/documenti/carica-documento`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elimina un documento caricato
     * 
     * @param idDocumento id documento
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteDocumento(idDocumento: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteDocumento(idDocumento: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteDocumento(idDocumento: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteDocumento(idDocumento: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idDocumento === null || idDocumento === undefined) {
            throw new Error('Required parameter idDocumento was null or undefined when calling deleteDocumento.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idDocumento !== undefined && idDocumento !== null) {
            queryParameters = queryParameters.set('idDocumento', <any>idDocumento);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/documenti/documento`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * ricerca documenti
     * ricerca di documenti tramite parametri
     * @param tipoDocumento codice tipo documento
     * @param titolo titolo documento
     * @param idIdeaDiImpresa documenti relativi ad un&#x27;idea di impresa se non valorizzato restituisce i documenti visualizzabili da tutti
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDocumentiByParameters(tipoDocumento?: string, titolo?: string, idIdeaDiImpresa?: number, observe?: 'body', reportProgress?: boolean): Observable<Documento>;
    public getDocumentiByParameters(tipoDocumento?: string, titolo?: string, idIdeaDiImpresa?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Documento>>;
    public getDocumentiByParameters(tipoDocumento?: string, titolo?: string, idIdeaDiImpresa?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Documento>>;
    public getDocumentiByParameters(tipoDocumento?: string, titolo?: string, idIdeaDiImpresa?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (tipoDocumento !== undefined && tipoDocumento !== null) {
            queryParameters = queryParameters.set('tipoDocumento', <any>tipoDocumento);
        }
        if (titolo !== undefined && titolo !== null) {
            queryParameters = queryParameters.set('titolo', <any>titolo);
        }
        if (idIdeaDiImpresa !== undefined && idIdeaDiImpresa !== null) {
            queryParameters = queryParameters.set('idIdeaDiImpresa', <any>idIdeaDiImpresa);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Documento>('get',`${this.basePath}/documenti`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * scarica documento
     * restituisce il documento con id passato come parametro
     * @param idDocumento id documento
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDocumentoById(idDocumento: number, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public getDocumentoById(idDocumento: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public getDocumentoById(idDocumento: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public getDocumentoById(idDocumento: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idDocumento === null || idDocumento === undefined) {
            throw new Error('Required parameter idDocumento was null or undefined when calling getDocumentoById.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idDocumento !== undefined && idDocumento !== null) {
            queryParameters = queryParameters.set('idDocumento', <any>idDocumento);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream',
            'application/problem+json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Blob>('get',`${this.basePath}/documenti/documento`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco eventi calendario filtrati per parametri
     * elenco eventi calendario filtrati per parametri
     * @param dataDa data minima per la ricerca degli eventi
     * @param dataA data massima per la ricerca degli eventi
     * @param idOperatore id operatore
     * @param idSoggettoAttuatore id soggetto attuatore
     * @param pageIndex 
     * @param pageSize 
     * @param sortDirection 
     * @param orderBy 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getEventiCalendario(dataDa?: string, dataA?: string, idOperatore?: number, idSoggettoAttuatore?: number, pageIndex?: number, pageSize?: number, sortDirection?: string, orderBy?: string, observe?: 'body', reportProgress?: boolean): Observable<EventoCalendarioRicerca>;
    public getEventiCalendario(dataDa?: string, dataA?: string, idOperatore?: number, idSoggettoAttuatore?: number, pageIndex?: number, pageSize?: number, sortDirection?: string, orderBy?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EventoCalendarioRicerca>>;
    public getEventiCalendario(dataDa?: string, dataA?: string, idOperatore?: number, idSoggettoAttuatore?: number, pageIndex?: number, pageSize?: number, sortDirection?: string, orderBy?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EventoCalendarioRicerca>>;
    public getEventiCalendario(dataDa?: string, dataA?: string, idOperatore?: number, idSoggettoAttuatore?: number, pageIndex?: number, pageSize?: number, sortDirection?: string, orderBy?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {









        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (dataDa !== undefined && dataDa !== null) {
            queryParameters = queryParameters.set('dataDa', <any>dataDa);
        }
        if (dataA !== undefined && dataA !== null) {
            queryParameters = queryParameters.set('dataA', <any>dataA);
        }
        if (idOperatore !== undefined && idOperatore !== null) {
            queryParameters = queryParameters.set('idOperatore', <any>idOperatore);
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }
        if (pageIndex !== undefined && pageIndex !== null) {
            queryParameters = queryParameters.set('pageIndex', <any>pageIndex);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (sortDirection !== undefined && sortDirection !== null) {
            queryParameters = queryParameters.set('sortDirection', <any>sortDirection);
        }
        if (orderBy !== undefined && orderBy !== null) {
            queryParameters = queryParameters.set('orderBy', <any>orderBy);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<EventoCalendarioRicerca>('get',`${this.basePath}/file-ics/eventi-calendario`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * scarica documento
     * restituisce il documento con id passato come parametro
     * @param idFileIcs id file ics
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFileIcsById(idFileIcs: number, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public getFileIcsById(idFileIcs: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public getFileIcsById(idFileIcs: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public getFileIcsById(idFileIcs: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idFileIcs === null || idFileIcs === undefined) {
            throw new Error('Required parameter idFileIcs was null or undefined when calling getFileIcsById.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idFileIcs !== undefined && idFileIcs !== null) {
            queryParameters = queryParameters.set('idFileIcs', <any>idFileIcs);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream',
            'application/problem+json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Blob>('get',`${this.basePath}/file-ics/download`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * storico inserimento file ics
     * storico inserimento file ics
     * @param idSoggettoAttuatore id soggetto attuatore
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getStoricoCalendario(idSoggettoAttuatore?: number, observe?: 'body', reportProgress?: boolean): Observable<StoricoCalendario>;
    public getStoricoCalendario(idSoggettoAttuatore?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<StoricoCalendario>>;
    public getStoricoCalendario(idSoggettoAttuatore?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<StoricoCalendario>>;
    public getStoricoCalendario(idSoggettoAttuatore?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<StoricoCalendario>('get',`${this.basePath}/file-ics/storico`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * file ics tramite id
     * restituisci il file con l&#x27;id indicato
     * @param idFileIcs 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getStoricoFileIcsById(idFileIcs: number, observe?: 'body', reportProgress?: boolean): Observable<StoricoCalendario>;
    public getStoricoFileIcsById(idFileIcs: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<StoricoCalendario>>;
    public getStoricoFileIcsById(idFileIcs: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<StoricoCalendario>>;
    public getStoricoFileIcsById(idFileIcs: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idFileIcs === null || idFileIcs === undefined) {
            throw new Error('Required parameter idFileIcs was null or undefined when calling getStoricoFileIcsById.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idFileIcs !== undefined && idFileIcs !== null) {
            queryParameters = queryParameters.set('idFileIcs', <any>idFileIcs);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<StoricoCalendario>('get',`${this.basePath}/file-ics`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco tipi di documento
     * elenco tipi di documento
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTipiDocumento(observe?: 'body', reportProgress?: boolean): Observable<TipoDocumento>;
    public getTipiDocumento(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<TipoDocumento>>;
    public getTipiDocumento(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<TipoDocumento>>;
    public getTipiDocumento(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<TipoDocumento>('get',`${this.basePath}/documenti/tipi-documento`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * aggiornamento file calendario
     * aggiorna abilitazione e descrizione
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateFileIcs(body?: FileIcs, observe?: 'body', reportProgress?: boolean): Observable<FileIcs>;
    public updateFileIcs(body?: FileIcs, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<FileIcs>>;
    public updateFileIcs(body?: FileIcs, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FileIcs>>;
    public updateFileIcs(body?: FileIcs, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<FileIcs>('put',`${this.basePath}/file-ics`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
