/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Errore } from '../model/errore';
import { IdeaDiImpresaRicercaExtendedConTotale } from '../model/ideaDiImpresaRicercaExtendedConTotale';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class ExcelService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * esportazione del foglio excel
     * restituisce il file excel degli anagrafica cittadino
     * @param idIncontroPreaccoglienza 
     * @param codOperatore 
     * @param idSoggettoAttuatore 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public exportExcelAnagraficaCittadino(idIncontroPreaccoglienza: number, codOperatore: string, idSoggettoAttuatore?: string, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public exportExcelAnagraficaCittadino(idIncontroPreaccoglienza: number, codOperatore: string, idSoggettoAttuatore?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public exportExcelAnagraficaCittadino(idIncontroPreaccoglienza: number, codOperatore: string, idSoggettoAttuatore?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public exportExcelAnagraficaCittadino(idIncontroPreaccoglienza: number, codOperatore: string, idSoggettoAttuatore?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idIncontroPreaccoglienza === null || idIncontroPreaccoglienza === undefined) {
            throw new Error('Required parameter idIncontroPreaccoglienza was null or undefined when calling exportExcelAnagraficaCittadino.');
        }

        if (codOperatore === null || codOperatore === undefined) {
            throw new Error('Required parameter codOperatore was null or undefined when calling exportExcelAnagraficaCittadino.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idIncontroPreaccoglienza !== undefined && idIncontroPreaccoglienza !== null) {
            queryParameters = queryParameters.set('idIncontroPreaccoglienza', <any>idIncontroPreaccoglienza);
        }
        if (codOperatore !== undefined && codOperatore !== null) {
            queryParameters = queryParameters.set('codOperatore', <any>codOperatore);
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Blob>('get',`${this.basePath}/excel/esporta-excel-anagrafica-cittadino`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * esportazione del foglio excel
     * restituisce il file excel delle idee d&#x27;impresa
     * @param nomeOperatore 
     * @param dataDa 
     * @param dataA 
     * @param idSoggettoAttuatore 
     * @param idCodAreaTerritoriale 
     * @param idStatoIdea 
     * @param tipoReport 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public exportExcelIdeeImpresa(nomeOperatore?: string, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, idStatoIdea?: number, tipoReport?: string, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public exportExcelIdeeImpresa(nomeOperatore?: string, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, idStatoIdea?: number, tipoReport?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public exportExcelIdeeImpresa(nomeOperatore?: string, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, idStatoIdea?: number, tipoReport?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public exportExcelIdeeImpresa(nomeOperatore?: string, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, idStatoIdea?: number, tipoReport?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {








        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (nomeOperatore !== undefined && nomeOperatore !== null) {
            queryParameters = queryParameters.set('nomeOperatore', <any>nomeOperatore);
        }
        if (dataDa !== undefined && dataDa !== null) {
            queryParameters = queryParameters.set('dataDa', <any>dataDa.toISOString());
        }
        if (dataA !== undefined && dataA !== null) {
            queryParameters = queryParameters.set('dataA', <any>dataA.toISOString());
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }
        if (idCodAreaTerritoriale !== undefined && idCodAreaTerritoriale !== null) {
            queryParameters = queryParameters.set('idCodAreaTerritoriale', <any>idCodAreaTerritoriale);
        }
        if (idStatoIdea !== undefined && idStatoIdea !== null) {
            queryParameters = queryParameters.set('idStatoIdea', <any>idStatoIdea);
        }
        if (tipoReport !== undefined && tipoReport !== null) {
            queryParameters = queryParameters.set('tipoReport', <any>tipoReport);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Blob>('get',`${this.basePath}/reportistica/esporta-excel-idee-impresa`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * esportazione del foglio excel
     * restituisce il file excel dei questionari
     * @param idFase 
     * @param dataDa 
     * @param dataA 
     * @param idSoggettoAttuatore 
     * @param idCodAreaTerritoriale 
     * @param nomeOperatore 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public exportExcelQuestionari(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, nomeOperatore?: string, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public exportExcelQuestionari(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, nomeOperatore?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public exportExcelQuestionari(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, nomeOperatore?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public exportExcelQuestionari(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, nomeOperatore?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {







        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idFase !== undefined && idFase !== null) {
            queryParameters = queryParameters.set('idFase', <any>idFase);
        }
        if (dataDa !== undefined && dataDa !== null) {
            queryParameters = queryParameters.set('dataDa', <any>dataDa.toISOString());
        }
        if (dataA !== undefined && dataA !== null) {
            queryParameters = queryParameters.set('dataA', <any>dataA.toISOString());
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }
        if (idCodAreaTerritoriale !== undefined && idCodAreaTerritoriale !== null) {
            queryParameters = queryParameters.set('idCodAreaTerritoriale', <any>idCodAreaTerritoriale);
        }
        if (nomeOperatore !== undefined && nomeOperatore !== null) {
            queryParameters = queryParameters.set('nomeOperatore', <any>nomeOperatore);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Blob>('get',`${this.basePath}/reportistica/esporta-excel-questionari`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * esportazione del foglio excel
     * restituisce il file pdf per le presenze
     * @param idIncontroPreaccoglienza 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public exportPdfPresenze(idIncontroPreaccoglienza: number, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public exportPdfPresenze(idIncontroPreaccoglienza: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public exportPdfPresenze(idIncontroPreaccoglienza: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public exportPdfPresenze(idIncontroPreaccoglienza: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idIncontroPreaccoglienza === null || idIncontroPreaccoglienza === undefined) {
            throw new Error('Required parameter idIncontroPreaccoglienza was null or undefined when calling exportPdfPresenze.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idIncontroPreaccoglienza !== undefined && idIncontroPreaccoglienza !== null) {
            queryParameters = queryParameters.set('idIncontroPreaccoglienza', <any>idIncontroPreaccoglienza);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Blob>('get',`${this.basePath}/pdf/esporta-pdf-presenze`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * esportazione del foglio excel contenete i partecipanti dgli incontri
     * restituisce la lista degli incontri di preaccoglienza con il pritrto su tutti i cittadini
     * @param idIncontriPreaccoglienza codice area territoriale
     * @param codOperatore codice operatore
     * @param idSoggettoAttuatore id soggetto attuatore
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getExportIncontriPreaccoglienzaAnagrafica(idIncontriPreaccoglienza?: string, codOperatore?: string, idSoggettoAttuatore?: string, observe?: 'body', reportProgress?: boolean): Observable<Blob>;
    public getExportIncontriPreaccoglienzaAnagrafica(idIncontriPreaccoglienza?: string, codOperatore?: string, idSoggettoAttuatore?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Blob>>;
    public getExportIncontriPreaccoglienzaAnagrafica(idIncontriPreaccoglienza?: string, codOperatore?: string, idSoggettoAttuatore?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Blob>>;
    public getExportIncontriPreaccoglienzaAnagrafica(idIncontriPreaccoglienza?: string, codOperatore?: string, idSoggettoAttuatore?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idIncontriPreaccoglienza !== undefined && idIncontriPreaccoglienza !== null) {
            queryParameters = queryParameters.set('idIncontriPreaccoglienza', <any>idIncontriPreaccoglienza);
        }
        if (codOperatore !== undefined && codOperatore !== null) {
            queryParameters = queryParameters.set('codOperatore', <any>codOperatore);
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Blob>('get',`${this.basePath}/excel/export-preaccoglienza-anagrafica`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * esportazione del foglio excel
     * restituisce  idee d&#x27;impresa
     * @param dataDa 
     * @param dataA 
     * @param idSoggettoAttuatore 
     * @param idCodAreaTerritoriale 
     * @param idStatoIdea 
     * @param tipoReport 
     * @param pageIndex 
     * @param pageSize 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIdeeImpresa(dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, idStatoIdea?: number, tipoReport?: string, pageIndex?: number, pageSize?: number, observe?: 'body', reportProgress?: boolean): Observable<IdeaDiImpresaRicercaExtendedConTotale>;
    public getIdeeImpresa(dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, idStatoIdea?: number, tipoReport?: string, pageIndex?: number, pageSize?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IdeaDiImpresaRicercaExtendedConTotale>>;
    public getIdeeImpresa(dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, idStatoIdea?: number, tipoReport?: string, pageIndex?: number, pageSize?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IdeaDiImpresaRicercaExtendedConTotale>>;
    public getIdeeImpresa(dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, idStatoIdea?: number, tipoReport?: string, pageIndex?: number, pageSize?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {









        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (dataDa !== undefined && dataDa !== null) {
            queryParameters = queryParameters.set('dataDa', <any>dataDa.toISOString());
        }
        if (dataA !== undefined && dataA !== null) {
            queryParameters = queryParameters.set('dataA', <any>dataA.toISOString());
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }
        if (idCodAreaTerritoriale !== undefined && idCodAreaTerritoriale !== null) {
            queryParameters = queryParameters.set('idCodAreaTerritoriale', <any>idCodAreaTerritoriale);
        }
        if (idStatoIdea !== undefined && idStatoIdea !== null) {
            queryParameters = queryParameters.set('idStatoIdea', <any>idStatoIdea);
        }
        if (tipoReport !== undefined && tipoReport !== null) {
            queryParameters = queryParameters.set('tipoReport', <any>tipoReport);
        }
        if (pageIndex !== undefined && pageIndex !== null) {
            queryParameters = queryParameters.set('pageIndex', <any>pageIndex);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IdeaDiImpresaRicercaExtendedConTotale>('get',`${this.basePath}/reportistica/idee-impresa`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
