/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Errore } from '../model/errore';
import { FonteConoscenzaMip } from '../model/fonteConoscenzaMip';
import { IdeaDiImpresa } from '../model/ideaDiImpresa';
import { IdeaDiImpresaIncontroPreaccoglienza } from '../model/ideaDiImpresaIncontroPreaccoglienza';
import { IdeaDiImpresaRicerca } from '../model/ideaDiImpresaRicerca';
import { IdeaDiImpresaRicercaConTotale } from '../model/ideaDiImpresaRicercaConTotale';
import { ResgistraPresenze } from '../model/resgistraPresenze';
import { StatoIdeaDiImpresa } from '../model/statoIdeaDiImpresa';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class IdeeDiImpresaService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * elenco fonti conoscenza mip
     * elenco delle fonti conoscenza mip
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getFontiConoscenzaMip(observe?: 'body', reportProgress?: boolean): Observable<Array<FonteConoscenzaMip>>;
    public getFontiConoscenzaMip(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<FonteConoscenzaMip>>>;
    public getFontiConoscenzaMip(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<FonteConoscenzaMip>>>;
    public getFontiConoscenzaMip(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<FonteConoscenzaMip>>('get',`${this.basePath}/idee-di-impresa/fonti-conoscenza-mip`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * torna l&#x27;idea di impresa pasando come parametro l&#x27;id
     * torna l&#x27;idea di impresa pasando come parametro l&#x27;id
     * @param id id dell&#x27;idea di impresa a cercare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIdeaDiImpresaById(id: number, observe?: 'body', reportProgress?: boolean): Observable<IdeaDiImpresa>;
    public getIdeaDiImpresaById(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IdeaDiImpresa>>;
    public getIdeaDiImpresaById(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IdeaDiImpresa>>;
    public getIdeaDiImpresaById(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getIdeaDiImpresaById.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IdeaDiImpresa>('get',`${this.basePath}/idee-di-impresa/idea-di-impresa`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * torna l&#x27;elenco idea di impresa pasando come parametro l&#x27;id del cittadino
     * torna l&#x27;idea di impresa pasando come parametro l&#x27;id cittadino
     * @param idCittadino id del cittadino
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIdeaDiImpresaByIdCittadino(idCittadino: number, observe?: 'body', reportProgress?: boolean): Observable<IdeaDiImpresaRicerca>;
    public getIdeaDiImpresaByIdCittadino(idCittadino: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IdeaDiImpresaRicerca>>;
    public getIdeaDiImpresaByIdCittadino(idCittadino: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IdeaDiImpresaRicerca>>;
    public getIdeaDiImpresaByIdCittadino(idCittadino: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCittadino === null || idCittadino === undefined) {
            throw new Error('Required parameter idCittadino was null or undefined when calling getIdeaDiImpresaByIdCittadino.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idCittadino !== undefined && idCittadino !== null) {
            queryParameters = queryParameters.set('idCittadino', <any>idCittadino);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IdeaDiImpresaRicerca>('get',`${this.basePath}/idee-di-impresa/idea-di-impresa-cittadino`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * torna l&#x27;elenco idea di impresa pasando come parametro l&#x27;id incontro preaccoglienza
     * torna l&#x27;idea di impresa pasando come parametro l&#x27;id
     * @param idIncontroPreaccoglienza id dell&#x27;incontro preaccoglienza a cercare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIdeaDiImpresaByIdIncontroPreacc(idIncontroPreaccoglienza: number, observe?: 'body', reportProgress?: boolean): Observable<IdeaDiImpresaIncontroPreaccoglienza>;
    public getIdeaDiImpresaByIdIncontroPreacc(idIncontroPreaccoglienza: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IdeaDiImpresaIncontroPreaccoglienza>>;
    public getIdeaDiImpresaByIdIncontroPreacc(idIncontroPreaccoglienza: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IdeaDiImpresaIncontroPreaccoglienza>>;
    public getIdeaDiImpresaByIdIncontroPreacc(idIncontroPreaccoglienza: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idIncontroPreaccoglienza === null || idIncontroPreaccoglienza === undefined) {
            throw new Error('Required parameter idIncontroPreaccoglienza was null or undefined when calling getIdeaDiImpresaByIdIncontroPreacc.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idIncontroPreaccoglienza !== undefined && idIncontroPreaccoglienza !== null) {
            queryParameters = queryParameters.set('idIncontroPreaccoglienza', <any>idIncontroPreaccoglienza);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IdeaDiImpresaIncontroPreaccoglienza>('get',`${this.basePath}/idee-di-impresa/incontro-pre-accoglienza`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * torna l&#x27;elenco idea di impresa pasando diversi parametro di ricerca preaccoglienza
     * torna l&#x27;idea di impresa pasando diversi parametri di ricerca
     * @param pageIndex 
     * @param pageSize 
     * @param codAreaTerritoriale codice area territoriale
     * @param dataInseritaDa data minima per la ricerca degli idee
     * @param dataInseritaA data massima per la ricerca degli idee
     * @param ideaDiImpresa denominazione luogo dell&#x27;incontro
     * @param cittadinoNome dati del cittadino, nome
     * @param cittadinoCognome dati del cittadino, cognome
     * @param idStatoIdea stato di idea
     * @param statoPresenze stato presenza incontro preaccoglienza
     * @param idSoggettoAttuatore id soggetto attuatore / tutor scelto
     * @param idOperatore id operatore
     * @param orderBy 
     * @param sortDirection 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIdeaDiImpresaPerParametri(pageIndex: number, pageSize: number, codAreaTerritoriale?: string, dataInseritaDa?: string, dataInseritaA?: string, ideaDiImpresa?: string, cittadinoNome?: string, cittadinoCognome?: string, idStatoIdea?: number, statoPresenze?: string, idSoggettoAttuatore?: number, idOperatore?: number, orderBy?: string, sortDirection?: string, observe?: 'body', reportProgress?: boolean): Observable<IdeaDiImpresaRicercaConTotale>;
    public getIdeaDiImpresaPerParametri(pageIndex: number, pageSize: number, codAreaTerritoriale?: string, dataInseritaDa?: string, dataInseritaA?: string, ideaDiImpresa?: string, cittadinoNome?: string, cittadinoCognome?: string, idStatoIdea?: number, statoPresenze?: string, idSoggettoAttuatore?: number, idOperatore?: number, orderBy?: string, sortDirection?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IdeaDiImpresaRicercaConTotale>>;
    public getIdeaDiImpresaPerParametri(pageIndex: number, pageSize: number, codAreaTerritoriale?: string, dataInseritaDa?: string, dataInseritaA?: string, ideaDiImpresa?: string, cittadinoNome?: string, cittadinoCognome?: string, idStatoIdea?: number, statoPresenze?: string, idSoggettoAttuatore?: number, idOperatore?: number, orderBy?: string, sortDirection?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IdeaDiImpresaRicercaConTotale>>;
    public getIdeaDiImpresaPerParametri(pageIndex: number, pageSize: number, codAreaTerritoriale?: string, dataInseritaDa?: string, dataInseritaA?: string, ideaDiImpresa?: string, cittadinoNome?: string, cittadinoCognome?: string, idStatoIdea?: number, statoPresenze?: string, idSoggettoAttuatore?: number, idOperatore?: number, orderBy?: string, sortDirection?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (pageIndex === null || pageIndex === undefined) {
            throw new Error('Required parameter pageIndex was null or undefined when calling getIdeaDiImpresaPerParametri.');
        }

        if (pageSize === null || pageSize === undefined) {
            throw new Error('Required parameter pageSize was null or undefined when calling getIdeaDiImpresaPerParametri.');
        }













        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (codAreaTerritoriale !== undefined && codAreaTerritoriale !== null) {
            queryParameters = queryParameters.set('codAreaTerritoriale', <any>codAreaTerritoriale);
        }
        if (dataInseritaDa !== undefined && dataInseritaDa !== null) {
            queryParameters = queryParameters.set('dataInseritaDa', <any>dataInseritaDa);
        }
        if (dataInseritaA !== undefined && dataInseritaA !== null) {
            queryParameters = queryParameters.set('dataInseritaA', <any>dataInseritaA);
        }
        if (ideaDiImpresa !== undefined && ideaDiImpresa !== null) {
            queryParameters = queryParameters.set('ideaDiImpresa', <any>ideaDiImpresa);
        }
        if (cittadinoNome !== undefined && cittadinoNome !== null) {
            queryParameters = queryParameters.set('cittadinoNome', <any>cittadinoNome);
        }
        if (cittadinoCognome !== undefined && cittadinoCognome !== null) {
            queryParameters = queryParameters.set('cittadinoCognome', <any>cittadinoCognome);
        }
        if (idStatoIdea !== undefined && idStatoIdea !== null) {
            queryParameters = queryParameters.set('idStatoIdea', <any>idStatoIdea);
        }
        if (statoPresenze !== undefined && statoPresenze !== null) {
            queryParameters = queryParameters.set('statoPresenze', <any>statoPresenze);
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }
        if (idOperatore !== undefined && idOperatore !== null) {
            queryParameters = queryParameters.set('idOperatore', <any>idOperatore);
        }
        if (pageIndex !== undefined && pageIndex !== null) {
            queryParameters = queryParameters.set('pageIndex', <any>pageIndex);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (orderBy !== undefined && orderBy !== null) {
            queryParameters = queryParameters.set('orderBy', <any>orderBy);
        }
        if (sortDirection !== undefined && sortDirection !== null) {
            queryParameters = queryParameters.set('sortDirection', <any>sortDirection);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IdeaDiImpresaRicercaConTotale>('get',`${this.basePath}/idee-di-impresa/ricerca`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco stati idea di impresa
     * elenco degli stati idea di impresa
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getStatiIdeaDiImpresa(observe?: 'body', reportProgress?: boolean): Observable<Array<StatoIdeaDiImpresa>>;
    public getStatiIdeaDiImpresa(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<StatoIdeaDiImpresa>>>;
    public getStatiIdeaDiImpresa(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<StatoIdeaDiImpresa>>>;
    public getStatiIdeaDiImpresa(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<StatoIdeaDiImpresa>>('get',`${this.basePath}/idee-di-impresa/stati-idea-di-impresa`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce un&#x27;idea di impresa
     * inserisce un&#x27;idea di impresa
     * @param idCittadino id cittadino a collegare con l&#x27;idea di impresa
     * @param body idea di impresa a inserire
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertIdeaDiImpresa(idCittadino: number, body?: IdeaDiImpresa, observe?: 'body', reportProgress?: boolean): Observable<IdeaDiImpresa>;
    public insertIdeaDiImpresa(idCittadino: number, body?: IdeaDiImpresa, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IdeaDiImpresa>>;
    public insertIdeaDiImpresa(idCittadino: number, body?: IdeaDiImpresa, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IdeaDiImpresa>>;
    public insertIdeaDiImpresa(idCittadino: number, body?: IdeaDiImpresa, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCittadino === null || idCittadino === undefined) {
            throw new Error('Required parameter idCittadino was null or undefined when calling insertIdeaDiImpresa.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idCittadino !== undefined && idCittadino !== null) {
            queryParameters = queryParameters.set('idCittadino', <any>idCittadino);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<IdeaDiImpresa>('post',`${this.basePath}/idee-di-impresa/idea-di-impresa`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * registra le presenze ad un incontro
     * 
     * @param body idea di impresa a modificare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public registraPresenzeIncontro(body?: Array<ResgistraPresenze>, observe?: 'body', reportProgress?: boolean): Observable<ResgistraPresenze>;
    public registraPresenzeIncontro(body?: Array<ResgistraPresenze>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ResgistraPresenze>>;
    public registraPresenzeIncontro(body?: Array<ResgistraPresenze>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ResgistraPresenze>>;
    public registraPresenzeIncontro(body?: Array<ResgistraPresenze>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ResgistraPresenze>('put',`${this.basePath}/idee-di-impresa/registra-presenze`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * modifica un&#x27;idea di impresa
     * modifica un&#x27;idea di impresa
     * @param body idea di impresa a modificare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateIdeaDiImpresa(body?: IdeaDiImpresa, observe?: 'body', reportProgress?: boolean): Observable<IdeaDiImpresa>;
    public updateIdeaDiImpresa(body?: IdeaDiImpresa, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IdeaDiImpresa>>;
    public updateIdeaDiImpresa(body?: IdeaDiImpresa, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IdeaDiImpresa>>;
    public updateIdeaDiImpresa(body?: IdeaDiImpresa, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<IdeaDiImpresa>('put',`${this.basePath}/idee-di-impresa/idea-di-impresa`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
