/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CittadinoIncontroPreaccoglienza } from '../model/cittadinoIncontroPreaccoglienza';
import { Errore } from '../model/errore';
import { IncontroPreAccoglienzaInsert } from '../model/incontroPreAccoglienzaInsert';
import { IncontroPreaccoglienza } from '../model/incontroPreaccoglienza';
import { IncontroPreaccoglienzaRicerca } from '../model/incontroPreaccoglienzaRicerca';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class IncontriPreaccoglienzaService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * elimina un inconro di preaccoglienza
     * 
     * @param idIncontroPreaccoglienza id incontro da eliminare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteIncontroPreaccoglienzaById(idIncontroPreaccoglienza: number, observe?: 'body', reportProgress?: boolean): Observable<IncontroPreAccoglienzaInsert>;
    public deleteIncontroPreaccoglienzaById(idIncontroPreaccoglienza: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncontroPreAccoglienzaInsert>>;
    public deleteIncontroPreaccoglienzaById(idIncontroPreaccoglienza: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncontroPreAccoglienzaInsert>>;
    public deleteIncontroPreaccoglienzaById(idIncontroPreaccoglienza: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idIncontroPreaccoglienza === null || idIncontroPreaccoglienza === undefined) {
            throw new Error('Required parameter idIncontroPreaccoglienza was null or undefined when calling deleteIncontroPreaccoglienzaById.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idIncontroPreaccoglienza !== undefined && idIncontroPreaccoglienza !== null) {
            queryParameters = queryParameters.set('idIncontroPreaccoglienza', <any>idIncontroPreaccoglienza);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IncontroPreAccoglienzaInsert>('delete',`${this.basePath}/incontri-preaccoglienza/incontro-preaccoglienza`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * torna l&#x27;incontro di preaccoglienza relazionato al cittadino passando  l&#x27;id cittadino_incontro_preaccoglienza
     * torna l&#x27;incontro di preaccoglienza relazionato al cittadino passando  l&#x27;id cittadino_incontro_preaccoglienza
     * @param id id cittadino incontro preaccoglienza
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCittadinoIncontroPreaccoglienza(id: number, observe?: 'body', reportProgress?: boolean): Observable<CittadinoIncontroPreaccoglienza>;
    public getCittadinoIncontroPreaccoglienza(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CittadinoIncontroPreaccoglienza>>;
    public getCittadinoIncontroPreaccoglienza(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CittadinoIncontroPreaccoglienza>>;
    public getCittadinoIncontroPreaccoglienza(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getCittadinoIncontroPreaccoglienza.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<CittadinoIncontroPreaccoglienza>('get',`${this.basePath}/incontri-preaccoglienza/cittadino-incontro-preaccoglienza`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco incontri preaccoglienza per mostrare al cittadino
     * elenco incontri preaccoglienza per mostrare al cittadino per scegliere l&#x27;incontro per asistere
     * @param codAreaTerritoriale codice area territoriale
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIncontriPreaccoglienzaByAreaTerritoriale(codAreaTerritoriale?: string, observe?: 'body', reportProgress?: boolean): Observable<IncontroPreaccoglienza>;
    public getIncontriPreaccoglienzaByAreaTerritoriale(codAreaTerritoriale?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncontroPreaccoglienza>>;
    public getIncontriPreaccoglienzaByAreaTerritoriale(codAreaTerritoriale?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncontroPreaccoglienza>>;
    public getIncontriPreaccoglienzaByAreaTerritoriale(codAreaTerritoriale?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (codAreaTerritoriale !== undefined && codAreaTerritoriale !== null) {
            queryParameters = queryParameters.set('codAreaTerritoriale', <any>codAreaTerritoriale);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IncontroPreaccoglienza>('get',`${this.basePath}/incontri-preaccoglienza/incontri-preaccoglienza-disponibile`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco incontri preaccoglienza con parametri
     * elenco degli incontri di preaccoglienza filtrati per parametri
     * @param codAreaTerritoriale codice area territoriale
     * @param dataIncontroDa data minima per la ricerca degli incontri
     * @param dataIncontroA data massima per la ricerca degli incontri
     * @param luogo id luogo incontro
     * @param idOperatore id operatore
     * @param idSoggettoAttuatore id soggetto attuatore
     * @param pageIndex 
     * @param pageSize 
     * @param orderBy 
     * @param sortDirection 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIncontriPreaccoglienzaByParameters(codAreaTerritoriale?: string, dataIncontroDa?: string, dataIncontroA?: string, luogo?: number, idOperatore?: string, idSoggettoAttuatore?: string, pageIndex?: number, pageSize?: number, orderBy?: string, sortDirection?: string, observe?: 'body', reportProgress?: boolean): Observable<IncontroPreaccoglienzaRicerca>;
    public getIncontriPreaccoglienzaByParameters(codAreaTerritoriale?: string, dataIncontroDa?: string, dataIncontroA?: string, luogo?: number, idOperatore?: string, idSoggettoAttuatore?: string, pageIndex?: number, pageSize?: number, orderBy?: string, sortDirection?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncontroPreaccoglienzaRicerca>>;
    public getIncontriPreaccoglienzaByParameters(codAreaTerritoriale?: string, dataIncontroDa?: string, dataIncontroA?: string, luogo?: number, idOperatore?: string, idSoggettoAttuatore?: string, pageIndex?: number, pageSize?: number, orderBy?: string, sortDirection?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncontroPreaccoglienzaRicerca>>;
    public getIncontriPreaccoglienzaByParameters(codAreaTerritoriale?: string, dataIncontroDa?: string, dataIncontroA?: string, luogo?: number, idOperatore?: string, idSoggettoAttuatore?: string, pageIndex?: number, pageSize?: number, orderBy?: string, sortDirection?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {











        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (codAreaTerritoriale !== undefined && codAreaTerritoriale !== null) {
            queryParameters = queryParameters.set('codAreaTerritoriale', <any>codAreaTerritoriale);
        }
        if (dataIncontroDa !== undefined && dataIncontroDa !== null) {
            queryParameters = queryParameters.set('dataIncontroDa', <any>dataIncontroDa);
        }
        if (dataIncontroA !== undefined && dataIncontroA !== null) {
            queryParameters = queryParameters.set('dataIncontroA', <any>dataIncontroA);
        }
        if (luogo !== undefined && luogo !== null) {
            queryParameters = queryParameters.set('luogo', <any>luogo);
        }
        if (idOperatore !== undefined && idOperatore !== null) {
            queryParameters = queryParameters.set('idOperatore', <any>idOperatore);
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }
        if (pageIndex !== undefined && pageIndex !== null) {
            queryParameters = queryParameters.set('pageIndex', <any>pageIndex);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }
        if (orderBy !== undefined && orderBy !== null) {
            queryParameters = queryParameters.set('orderBy', <any>orderBy);
        }
        if (sortDirection !== undefined && sortDirection !== null) {
            queryParameters = queryParameters.set('sortDirection', <any>sortDirection);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IncontroPreaccoglienzaRicerca>('get',`${this.basePath}/incontri-preaccoglienza`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * torna l&#x27;incontro di preaccoglienza  passando  l&#x27;id come parametro
     * torna l&#x27;incontro di preaccoglienza passando  l&#x27;id come parametro
     * @param id id incontro preaccoglienza
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIncontroPreaccoglienza(id: number, observe?: 'body', reportProgress?: boolean): Observable<IncontroPreAccoglienzaInsert>;
    public getIncontroPreaccoglienza(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncontroPreAccoglienzaInsert>>;
    public getIncontroPreaccoglienza(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncontroPreAccoglienzaInsert>>;
    public getIncontroPreaccoglienza(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getIncontroPreaccoglienza.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (id !== undefined && id !== null) {
            queryParameters = queryParameters.set('id', <any>id);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IncontroPreAccoglienzaInsert>('get',`${this.basePath}/incontri-preaccoglienza/incontro-preaccoglienza`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * torna l&#x27;incontro di preaccoglienza relazionato al cittadino passando  l&#x27;id del cittadino come parametro
     * torna l&#x27;incontro di preaccoglienza relazionato al cittadino passando  l&#x27;id del cittadino come parametro
     * @param idCittadino id del cittadino
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIncontroPreaccoglienzaPerCittadino(idCittadino: number, observe?: 'body', reportProgress?: boolean): Observable<IncontroPreaccoglienza>;
    public getIncontroPreaccoglienzaPerCittadino(idCittadino: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncontroPreaccoglienza>>;
    public getIncontroPreaccoglienzaPerCittadino(idCittadino: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncontroPreaccoglienza>>;
    public getIncontroPreaccoglienzaPerCittadino(idCittadino: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCittadino === null || idCittadino === undefined) {
            throw new Error('Required parameter idCittadino was null or undefined when calling getIncontroPreaccoglienzaPerCittadino.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idCittadino !== undefined && idCittadino !== null) {
            queryParameters = queryParameters.set('idCittadino', <any>idCittadino);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IncontroPreaccoglienza>('get',`${this.basePath}/incontri-preaccoglienza/incontro-preaccoglienza-per-cittadino`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * torna l&#x27;incontro di preaccoglienza relazionato al cittadino passando  l&#x27;id ide d&#x27;impresa come parametro
     * torna l&#x27;incontro di preaccoglienza relazionato al cittadino passando  l&#x27;id della idea di impresa
     * @param idIdeaImpresa id idea d&#x27;impresa
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getIncontroPreaccoglienzaPerIdeaImpresa(idIdeaImpresa: number, observe?: 'body', reportProgress?: boolean): Observable<IncontroPreaccoglienza>;
    public getIncontroPreaccoglienzaPerIdeaImpresa(idIdeaImpresa: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncontroPreaccoglienza>>;
    public getIncontroPreaccoglienzaPerIdeaImpresa(idIdeaImpresa: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncontroPreaccoglienza>>;
    public getIncontroPreaccoglienzaPerIdeaImpresa(idIdeaImpresa: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idIdeaImpresa === null || idIdeaImpresa === undefined) {
            throw new Error('Required parameter idIdeaImpresa was null or undefined when calling getIncontroPreaccoglienzaPerIdeaImpresa.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idIdeaImpresa !== undefined && idIdeaImpresa !== null) {
            queryParameters = queryParameters.set('idIdeaImpresa', <any>idIdeaImpresa);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IncontroPreaccoglienza>('get',`${this.basePath}/incontri-preaccoglienza/incontro-preaccoglienza-per-idea-impresa`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce un&#x27;incontro di preaccoglienza relazionato al cittadino
     * inserisce un&#x27;incontro di preaccoglienza relazionato al cittadino
     * @param body CittadinoIncontroPreaccoglienza a inserire
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertCittadinoIncontroPreaccoglienza(body?: CittadinoIncontroPreaccoglienza, observe?: 'body', reportProgress?: boolean): Observable<CittadinoIncontroPreaccoglienza>;
    public insertCittadinoIncontroPreaccoglienza(body?: CittadinoIncontroPreaccoglienza, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CittadinoIncontroPreaccoglienza>>;
    public insertCittadinoIncontroPreaccoglienza(body?: CittadinoIncontroPreaccoglienza, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CittadinoIncontroPreaccoglienza>>;
    public insertCittadinoIncontroPreaccoglienza(body?: CittadinoIncontroPreaccoglienza, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CittadinoIncontroPreaccoglienza>('post',`${this.basePath}/incontri-preaccoglienza/cittadino-incontro-preaccoglienza`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce un&#x27;incontro di preaccoglienza
     * inserisce un&#x27;incontro di preaccoglienza
     * @param body IncontroPreaccoglienza a inserire
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertIncontroPreaccoglienza(body?: IncontroPreAccoglienzaInsert, observe?: 'body', reportProgress?: boolean): Observable<IncontroPreAccoglienzaInsert>;
    public insertIncontroPreaccoglienza(body?: IncontroPreAccoglienzaInsert, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncontroPreAccoglienzaInsert>>;
    public insertIncontroPreaccoglienza(body?: IncontroPreAccoglienzaInsert, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncontroPreAccoglienzaInsert>>;
    public insertIncontroPreaccoglienza(body?: IncontroPreAccoglienzaInsert, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<IncontroPreAccoglienzaInsert>('post',`${this.basePath}/incontri-preaccoglienza/incontro-preaccoglienza`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * manda un comunicato a tutti i partecipanti all&#x27;incontro di preaccoglienza
     * torna l&#x27;incontro di preaccoglienza relazionato al cittadino passando  l&#x27;id del cittadino come parametro
     * @param oggetto oggetto del comunicato
     * @param corpo corpo del comunicato
     * @param idCittadino id cittadino
     * @param idIncontroPreaccoglienza id incontro
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inviaComunicatoPartecipanti(oggetto: string, corpo: string, idCittadino?: number, idIncontroPreaccoglienza?: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public inviaComunicatoPartecipanti(oggetto: string, corpo: string, idCittadino?: number, idIncontroPreaccoglienza?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public inviaComunicatoPartecipanti(oggetto: string, corpo: string, idCittadino?: number, idIncontroPreaccoglienza?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public inviaComunicatoPartecipanti(oggetto: string, corpo: string, idCittadino?: number, idIncontroPreaccoglienza?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (oggetto === null || oggetto === undefined) {
            throw new Error('Required parameter oggetto was null or undefined when calling inviaComunicatoPartecipanti.');
        }

        if (corpo === null || corpo === undefined) {
            throw new Error('Required parameter corpo was null or undefined when calling inviaComunicatoPartecipanti.');
        }



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idCittadino !== undefined && idCittadino !== null) {
            queryParameters = queryParameters.set('idCittadino', <any>idCittadino);
        }
        if (idIncontroPreaccoglienza !== undefined && idIncontroPreaccoglienza !== null) {
            queryParameters = queryParameters.set('idIncontroPreaccoglienza', <any>idIncontroPreaccoglienza);
        }
        if (oggetto !== undefined && oggetto !== null) {
            queryParameters = queryParameters.set('oggetto', <any>oggetto);
        }
        if (corpo !== undefined && corpo !== null) {
            queryParameters = queryParameters.set('corpo', <any>corpo);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('post',`${this.basePath}/incontri-preaccoglienza/incontro-preaccoglienza-invia-comunicato`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * modifica un&#x27;incontro di preaccoglienza relazionato al cittadino
     * modifica un&#x27;incontro di preaccoglienza relazionato al cittadino
     * @param body CittadinoIncontroPreaccoglienza a modificare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateCittadinoIncontroPreaccoglienza(body?: CittadinoIncontroPreaccoglienza, observe?: 'body', reportProgress?: boolean): Observable<CittadinoIncontroPreaccoglienza>;
    public updateCittadinoIncontroPreaccoglienza(body?: CittadinoIncontroPreaccoglienza, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CittadinoIncontroPreaccoglienza>>;
    public updateCittadinoIncontroPreaccoglienza(body?: CittadinoIncontroPreaccoglienza, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CittadinoIncontroPreaccoglienza>>;
    public updateCittadinoIncontroPreaccoglienza(body?: CittadinoIncontroPreaccoglienza, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CittadinoIncontroPreaccoglienza>('put',`${this.basePath}/incontri-preaccoglienza/cittadino-incontro-preaccoglienza`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * modifica un&#x27;incontro di preaccoglienza
     * modifica un&#x27;incontro di preaccoglienza
     * @param body IncontroPreaccoglienza a modificare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateIncontroPreaccoglienza(body?: IncontroPreAccoglienzaInsert, observe?: 'body', reportProgress?: boolean): Observable<IncontroPreAccoglienzaInsert>;
    public updateIncontroPreaccoglienza(body?: IncontroPreAccoglienzaInsert, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IncontroPreAccoglienzaInsert>>;
    public updateIncontroPreaccoglienza(body?: IncontroPreAccoglienzaInsert, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IncontroPreAccoglienzaInsert>>;
    public updateIncontroPreaccoglienza(body?: IncontroPreAccoglienzaInsert, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<IncontroPreAccoglienzaInsert>('put',`${this.basePath}/incontri-preaccoglienza/incontro-preaccoglienza`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
