/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Errore } from '../model/errore';
import { Operatore } from '../model/operatore';
import { OperatoreIncontroPreaccoglienza } from '../model/operatoreIncontroPreaccoglienza';
import { SoggettoAttuatore } from '../model/soggettoAttuatore';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class OperatoriService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * cancella / disassocia un operatore a un incontro preaccoglienza
     * delete a pet
     * @param idOperatore 
     * @param idIncontroPreaccoglienza 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteOperatoreIncontroPreaccoglienza(idOperatore: number, idIncontroPreaccoglienza: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteOperatoreIncontroPreaccoglienza(idOperatore: number, idIncontroPreaccoglienza: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteOperatoreIncontroPreaccoglienza(idOperatore: number, idIncontroPreaccoglienza: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteOperatoreIncontroPreaccoglienza(idOperatore: number, idIncontroPreaccoglienza: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idOperatore === null || idOperatore === undefined) {
            throw new Error('Required parameter idOperatore was null or undefined when calling deleteOperatoreIncontroPreaccoglienza.');
        }

        if (idIncontroPreaccoglienza === null || idIncontroPreaccoglienza === undefined) {
            throw new Error('Required parameter idIncontroPreaccoglienza was null or undefined when calling deleteOperatoreIncontroPreaccoglienza.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idOperatore !== undefined && idOperatore !== null) {
            queryParameters = queryParameters.set('idOperatore', <any>idOperatore);
        }
        if (idIncontroPreaccoglienza !== undefined && idIncontroPreaccoglienza !== null) {
            queryParameters = queryParameters.set('idIncontroPreaccoglienza', <any>idIncontroPreaccoglienza);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/operatori/operatore-incontro-preaccoglienza`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * torna l&#x27;operatore pasando come parametro l&#x27;id
     * torna l&#x27;operaore pasando come parametro l&#x27;id
     * @param idOperatore id dell&#x27;operatore a cercare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOperatoreById(idOperatore: number, observe?: 'body', reportProgress?: boolean): Observable<Operatore>;
    public getOperatoreById(idOperatore: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Operatore>>;
    public getOperatoreById(idOperatore: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Operatore>>;
    public getOperatoreById(idOperatore: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idOperatore === null || idOperatore === undefined) {
            throw new Error('Required parameter idOperatore was null or undefined when calling getOperatoreById.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idOperatore !== undefined && idOperatore !== null) {
            queryParameters = queryParameters.set('idOperatore', <any>idOperatore);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Operatore>('get',`${this.basePath}/operatori/operatore`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco tutti operatori
     * elenco dei operatori
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOperatori(observe?: 'body', reportProgress?: boolean): Observable<Operatore>;
    public getOperatori(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Operatore>>;
    public getOperatori(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Operatore>>;
    public getOperatori(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Operatore>('get',`${this.basePath}/operatori`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco operatori relazionato a un incontro preaccoglienza passando l&#x27;id del incontro come parametro
     * torna l&#x27;elenco operatori relazionato a un incontro preaccoglienza passando l&#x27;id del incontro come parametro
     * @param idIncontroPreacc id incontro preaccoglienza
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOperatoriIncontroPreaccoglienza(idIncontroPreacc: number, observe?: 'body', reportProgress?: boolean): Observable<Operatore>;
    public getOperatoriIncontroPreaccoglienza(idIncontroPreacc: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Operatore>>;
    public getOperatoriIncontroPreaccoglienza(idIncontroPreacc: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Operatore>>;
    public getOperatoriIncontroPreaccoglienza(idIncontroPreacc: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idIncontroPreacc === null || idIncontroPreacc === undefined) {
            throw new Error('Required parameter idIncontroPreacc was null or undefined when calling getOperatoriIncontroPreaccoglienza.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idIncontroPreacc !== undefined && idIncontroPreacc !== null) {
            queryParameters = queryParameters.set('idIncontroPreacc', <any>idIncontroPreacc);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Operatore>('get',`${this.basePath}/operatori/operatore-incontro-preaccoglienza`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco tutti operatori passando diversi paramatri per la ricerca
     * elenco dei operatori passando diversi paramatri per la ricerca
     * @param nome nome operatore
     * @param cognome cognome operatore
     * @param email email operatore
     * @param codiceFiscale codice fiscale operatore
     * @param idOperatore id operatore
     * @param soggetto per filtrare in base al soggetto
     * @param abilitato per filtrare in base a la disabilitazione
     * @param idSoggettoAttuatore id soggetto attuatore
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOperatoriRicerca(nome?: string, cognome?: string, email?: string, codiceFiscale?: string, idOperatore?: number, soggetto?: string, abilitato?: string, idSoggettoAttuatore?: number, observe?: 'body', reportProgress?: boolean): Observable<Operatore>;
    public getOperatoriRicerca(nome?: string, cognome?: string, email?: string, codiceFiscale?: string, idOperatore?: number, soggetto?: string, abilitato?: string, idSoggettoAttuatore?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Operatore>>;
    public getOperatoriRicerca(nome?: string, cognome?: string, email?: string, codiceFiscale?: string, idOperatore?: number, soggetto?: string, abilitato?: string, idSoggettoAttuatore?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Operatore>>;
    public getOperatoriRicerca(nome?: string, cognome?: string, email?: string, codiceFiscale?: string, idOperatore?: number, soggetto?: string, abilitato?: string, idSoggettoAttuatore?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {









        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (nome !== undefined && nome !== null) {
            queryParameters = queryParameters.set('nome', <any>nome);
        }
        if (cognome !== undefined && cognome !== null) {
            queryParameters = queryParameters.set('cognome', <any>cognome);
        }
        if (email !== undefined && email !== null) {
            queryParameters = queryParameters.set('email', <any>email);
        }
        if (codiceFiscale !== undefined && codiceFiscale !== null) {
            queryParameters = queryParameters.set('codiceFiscale', <any>codiceFiscale);
        }
        if (idOperatore !== undefined && idOperatore !== null) {
            queryParameters = queryParameters.set('idOperatore', <any>idOperatore);
        }
        if (soggetto !== undefined && soggetto !== null) {
            queryParameters = queryParameters.set('soggetto', <any>soggetto);
        }
        if (abilitato !== undefined && abilitato !== null) {
            queryParameters = queryParameters.set('abilitato', <any>abilitato);
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Operatore>('get',`${this.basePath}/operatori/ricerca-operatori`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * torna l&#x27;operatore pasando come parametro l&#x27;id
     * torna l&#x27;elenco soggetti attuatori  come parametro l&#x27;id
     * @param idOperatore id dell&#x27;operatore a cercare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSoggettiAttuatoriForOperatoreById(idOperatore: number, observe?: 'body', reportProgress?: boolean): Observable<Array<SoggettoAttuatore>>;
    public getSoggettiAttuatoriForOperatoreById(idOperatore: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SoggettoAttuatore>>>;
    public getSoggettiAttuatoriForOperatoreById(idOperatore: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SoggettoAttuatore>>>;
    public getSoggettiAttuatoriForOperatoreById(idOperatore: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idOperatore === null || idOperatore === undefined) {
            throw new Error('Required parameter idOperatore was null or undefined when calling getSoggettiAttuatoriForOperatoreById.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idOperatore !== undefined && idOperatore !== null) {
            queryParameters = queryParameters.set('idOperatore', <any>idOperatore);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<SoggettoAttuatore>>('get',`${this.basePath}/operatori/operatore/soggetti-attutatori`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce un&#x27;operatore
     * inserisce un&#x27;operatore
     * @param body operatore a inserire
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertOperatore(body?: Operatore, observe?: 'body', reportProgress?: boolean): Observable<Operatore>;
    public insertOperatore(body?: Operatore, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Operatore>>;
    public insertOperatore(body?: Operatore, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Operatore>>;
    public insertOperatore(body?: Operatore, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Operatore>('post',`${this.basePath}/operatori/operatore`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * inserisce/associa un&#x27;operatore ad un incontro preaccoglienza
     * inserisce/associa un&#x27;operatore ad un incontro preaccoglienza
     * @param body OperatoreIncontroPreaccoglienza a inserire
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public insertOperatoreIncontroPreaccoglienza(body?: OperatoreIncontroPreaccoglienza, observe?: 'body', reportProgress?: boolean): Observable<OperatoreIncontroPreaccoglienza>;
    public insertOperatoreIncontroPreaccoglienza(body?: OperatoreIncontroPreaccoglienza, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<OperatoreIncontroPreaccoglienza>>;
    public insertOperatoreIncontroPreaccoglienza(body?: OperatoreIncontroPreaccoglienza, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<OperatoreIncontroPreaccoglienza>>;
    public insertOperatoreIncontroPreaccoglienza(body?: OperatoreIncontroPreaccoglienza, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<OperatoreIncontroPreaccoglienza>('post',`${this.basePath}/operatori/operatore-incontro-preaccoglienza`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * modifica un&#x27;operatore
     * modifica un&#x27;operatore
     * @param body operatore a modificare
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateOperaotre(body?: Operatore, observe?: 'body', reportProgress?: boolean): Observable<Operatore>;
    public updateOperaotre(body?: Operatore, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Operatore>>;
    public updateOperaotre(body?: Operatore, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Operatore>>;
    public updateOperaotre(body?: Operatore, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Operatore>('put',`${this.basePath}/operatori/operatore`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
