/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Errore } from '../model/errore';
import { Questionario } from '../model/questionario';
import { ReportQuestionario } from '../model/reportQuestionario';
import { RispostaCompilazione } from '../model/rispostaCompilazione';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class QuestionarioService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * restituzione domande e risposte questionario fase 1
     * restituisce domande e risposte questionario fase 1
     * @param idFase 
     * @param dataDa 
     * @param dataA 
     * @param idSoggettoAttuatore 
     * @param idCodAreaTerritoriale 
     * @param pageIndex 
     * @param pageSize 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDomandeRisposte(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, pageIndex?: number, pageSize?: number, observe?: 'body', reportProgress?: boolean): Observable<ReportQuestionario>;
    public getDomandeRisposte(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, pageIndex?: number, pageSize?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReportQuestionario>>;
    public getDomandeRisposte(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, pageIndex?: number, pageSize?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReportQuestionario>>;
    public getDomandeRisposte(idFase?: number, dataDa?: Date, dataA?: Date, idSoggettoAttuatore?: number, idCodAreaTerritoriale?: string, pageIndex?: number, pageSize?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {








        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idFase !== undefined && idFase !== null) {
            queryParameters = queryParameters.set('idFase', <any>idFase);
        }
        if (dataDa !== undefined && dataDa !== null) {
            queryParameters = queryParameters.set('dataDa', <any>dataDa.toISOString());
        }
        if (dataA !== undefined && dataA !== null) {
            queryParameters = queryParameters.set('dataA', <any>dataA.toISOString());
        }
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }
        if (idCodAreaTerritoriale !== undefined && idCodAreaTerritoriale !== null) {
            queryParameters = queryParameters.set('idCodAreaTerritoriale', <any>idCodAreaTerritoriale);
        }
        if (pageIndex !== undefined && pageIndex !== null) {
            queryParameters = queryParameters.set('pageIndex', <any>pageIndex);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('pageSize', <any>pageSize);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/octet-stream',
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ReportQuestionario>('get',`${this.basePath}/reportistica/questionari`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Ottiene il questionario corrente basato sulla fase in cui si trova il cittadino
     * 
     * @param idCittadino CF del cittadino fornito nell&#x27;header.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getQuestionarioCorrente(idCittadino: number, observe?: 'body', reportProgress?: boolean): Observable<Questionario>;
    public getQuestionarioCorrente(idCittadino: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Questionario>>;
    public getQuestionarioCorrente(idCittadino: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Questionario>>;
    public getQuestionarioCorrente(idCittadino: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCittadino === null || idCittadino === undefined) {
            throw new Error('Required parameter idCittadino was null or undefined when calling getQuestionarioCorrente.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idCittadino !== undefined && idCittadino !== null) {
            queryParameters = queryParameters.set('idCittadino', <any>idCittadino);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Questionario>('get',`${this.basePath}/questionario/corrente`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Ottiene l&#x27;ID fase corrente per il cittadino
     * 
     * @param idCittadino cf del cittadino fornito nell&#x27;header.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getQuestionarioFaseCorrente(idCittadino: number, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public getQuestionarioFaseCorrente(idCittadino: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public getQuestionarioFaseCorrente(idCittadino: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public getQuestionarioFaseCorrente(idCittadino: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idCittadino === null || idCittadino === undefined) {
            throw new Error('Required parameter idCittadino was null or undefined when calling getQuestionarioFaseCorrente.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idCittadino !== undefined && idCittadino !== null) {
            queryParameters = queryParameters.set('idCittadino', <any>idCittadino);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<number>('get',`${this.basePath}/questionario/fase-corrente`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Salva le risposte del cittadino al questionario
     * 
     * @param body 
     * @param idCittadino CF del cittadino fornito nell&#x27;header.
     * @param idQuestionario 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public salvaRisposteQuestionario(body: Array<RispostaCompilazione>, idCittadino: number, idQuestionario: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public salvaRisposteQuestionario(body: Array<RispostaCompilazione>, idCittadino: number, idQuestionario: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public salvaRisposteQuestionario(body: Array<RispostaCompilazione>, idCittadino: number, idQuestionario: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public salvaRisposteQuestionario(body: Array<RispostaCompilazione>, idCittadino: number, idQuestionario: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling salvaRisposteQuestionario.');
        }

        if (idCittadino === null || idCittadino === undefined) {
            throw new Error('Required parameter idCittadino was null or undefined when calling salvaRisposteQuestionario.');
        }

        if (idQuestionario === null || idQuestionario === undefined) {
            throw new Error('Required parameter idQuestionario was null or undefined when calling salvaRisposteQuestionario.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idCittadino !== undefined && idCittadino !== null) {
            queryParameters = queryParameters.set('idCittadino', <any>idCittadino);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/questionario/${encodeURIComponent(String(idQuestionario))}/risposte`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * manda mail ai cittadini secondo un parametro
     * 
     * @param codEmail codice email da inviare
     * @param body cittadini a cui mandare l&#x27;email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sendMail(codEmail: string, body?: Array<number>, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public sendMail(codEmail: string, body?: Array<number>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public sendMail(codEmail: string, body?: Array<number>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public sendMail(codEmail: string, body?: Array<number>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (codEmail === null || codEmail === undefined) {
            throw new Error('Required parameter codEmail was null or undefined when calling sendMail.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (codEmail !== undefined && codEmail !== null) {
            queryParameters = queryParameters.set('codEmail', <any>codEmail);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post',`${this.basePath}/questionario/send-email-cittadini`,
            {
                body: body,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
