/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Errore } from '../model/errore';
import { Operatore } from '../model/operatore';
import { SoggettoAttuatore } from '../model/soggettoAttuatore';
import { SoggettoAttuatoreOperatore } from '../model/soggettoAttuatoreOperatore';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class SoggettiAttuatoreService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * cambia stato di disabilitazione del soggetto attuatore operatore
     * cambia stato di disabilitazione del soggetto attuatore operatore
     * @param idSoggettoAttuatore 
     * @param idOperatore 
     * @param idOperatoreDisabilitazione 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public cambiaStatoOperatoriSoggettoAttuatore(idSoggettoAttuatore: number, idOperatore: number, idOperatoreDisabilitazione: number, observe?: 'body', reportProgress?: boolean): Observable<SoggettoAttuatoreOperatore>;
    public cambiaStatoOperatoriSoggettoAttuatore(idSoggettoAttuatore: number, idOperatore: number, idOperatoreDisabilitazione: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SoggettoAttuatoreOperatore>>;
    public cambiaStatoOperatoriSoggettoAttuatore(idSoggettoAttuatore: number, idOperatore: number, idOperatoreDisabilitazione: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SoggettoAttuatoreOperatore>>;
    public cambiaStatoOperatoriSoggettoAttuatore(idSoggettoAttuatore: number, idOperatore: number, idOperatoreDisabilitazione: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSoggettoAttuatore === null || idSoggettoAttuatore === undefined) {
            throw new Error('Required parameter idSoggettoAttuatore was null or undefined when calling cambiaStatoOperatoriSoggettoAttuatore.');
        }

        if (idOperatore === null || idOperatore === undefined) {
            throw new Error('Required parameter idOperatore was null or undefined when calling cambiaStatoOperatoriSoggettoAttuatore.');
        }

        if (idOperatoreDisabilitazione === null || idOperatoreDisabilitazione === undefined) {
            throw new Error('Required parameter idOperatoreDisabilitazione was null or undefined when calling cambiaStatoOperatoriSoggettoAttuatore.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }
        if (idOperatore !== undefined && idOperatore !== null) {
            queryParameters = queryParameters.set('idOperatore', <any>idOperatore);
        }
        if (idOperatoreDisabilitazione !== undefined && idOperatoreDisabilitazione !== null) {
            queryParameters = queryParameters.set('idOperatoreDisabilitazione', <any>idOperatoreDisabilitazione);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SoggettoAttuatoreOperatore>('put',`${this.basePath}/soggetti-attuatore/operatore-soggetto-attuatore/cambio-stato-disabilitazione`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco operatori associato a un soggetto attuatore pasando l&#x27;id come parametro
     * elenco soggetti attuatori associato a un soggetto attuatore pasando l&#x27;id come parametro
     * @param idSoggettoAttuatore 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getOperatoriByIdSoggettoAttuatore(idSoggettoAttuatore: number, observe?: 'body', reportProgress?: boolean): Observable<Operatore>;
    public getOperatoriByIdSoggettoAttuatore(idSoggettoAttuatore: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Operatore>>;
    public getOperatoriByIdSoggettoAttuatore(idSoggettoAttuatore: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Operatore>>;
    public getOperatoriByIdSoggettoAttuatore(idSoggettoAttuatore: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idSoggettoAttuatore === null || idSoggettoAttuatore === undefined) {
            throw new Error('Required parameter idSoggettoAttuatore was null or undefined when calling getOperatoriByIdSoggettoAttuatore.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idSoggettoAttuatore !== undefined && idSoggettoAttuatore !== null) {
            queryParameters = queryParameters.set('idSoggettoAttuatore', <any>idSoggettoAttuatore);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Operatore>('get',`${this.basePath}/soggetti-attuatore/operatore-soggetto-attuatore`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco soggetti attuatori
     * elenco soggetti attuatori
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSoggettiAttuatori(observe?: 'body', reportProgress?: boolean): Observable<SoggettoAttuatore>;
    public getSoggettiAttuatori(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SoggettoAttuatore>>;
    public getSoggettiAttuatori(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SoggettoAttuatore>>;
    public getSoggettiAttuatori(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SoggettoAttuatore>('get',`${this.basePath}/soggetti-attuatore`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * elenco soggetto attuatore associati a un operatori pasando l&#x27;id operatore come parametro
     * elenco soggetti attuatori associato a un soggetto attuatore pasando l&#x27;id come parametro
     * @param idOperatore 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSoggettoAttuatoreByIdOperatori(idOperatore: number, observe?: 'body', reportProgress?: boolean): Observable<SoggettoAttuatore>;
    public getSoggettoAttuatoreByIdOperatori(idOperatore: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SoggettoAttuatore>>;
    public getSoggettoAttuatoreByIdOperatori(idOperatore: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SoggettoAttuatore>>;
    public getSoggettoAttuatoreByIdOperatori(idOperatore: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idOperatore === null || idOperatore === undefined) {
            throw new Error('Required parameter idOperatore was null or undefined when calling getSoggettoAttuatoreByIdOperatori.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idOperatore !== undefined && idOperatore !== null) {
            queryParameters = queryParameters.set('idOperatore', <any>idOperatore);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SoggettoAttuatore>('get',`${this.basePath}/soggetti-attuatore/soggetto-attuatore-per-operatore`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * modifica dati aggiuntivi
     * aggiorna mail e telefono del soggetto
     * @param body soggetto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateSoggettoAttuatore(body?: SoggettoAttuatore, observe?: 'body', reportProgress?: boolean): Observable<SoggettoAttuatore>;
    public updateSoggettoAttuatore(body?: SoggettoAttuatore, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SoggettoAttuatore>>;
    public updateSoggettoAttuatore(body?: SoggettoAttuatore, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SoggettoAttuatore>>;
    public updateSoggettoAttuatore(body?: SoggettoAttuatore, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SoggettoAttuatore>('put',`${this.basePath}/soggetti-attuatore`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
