/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Errore } from '../model/errore';
import { IdeaDiImpresa } from '../model/ideaDiImpresa';
import { Tutor } from '../model/tutor';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class TutorService {

    protected basePath = 'http://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * elenco tutor per mostrare al cittadino in base l&#x27;area territoriale
     * elenco tutor per mostrare al cittadino  in base l&#x27;area territoriale
     * @param codAreaTerritoriale codice area territoriale
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTutorPerAreaTerritoriale(codAreaTerritoriale?: string, observe?: 'body', reportProgress?: boolean): Observable<Tutor>;
    public getTutorPerAreaTerritoriale(codAreaTerritoriale?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Tutor>>;
    public getTutorPerAreaTerritoriale(codAreaTerritoriale?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Tutor>>;
    public getTutorPerAreaTerritoriale(codAreaTerritoriale?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (codAreaTerritoriale !== undefined && codAreaTerritoriale !== null) {
            queryParameters = queryParameters.set('codAreaTerritoriale', <any>codAreaTerritoriale);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Tutor>('get',`${this.basePath}/tutor/tutor-area-territoriale`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * tutor per id
     * tutor per id tutor
     * @param idTutor id tutor
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTutorPerId(idTutor: number, observe?: 'body', reportProgress?: boolean): Observable<Tutor>;
    public getTutorPerId(idTutor: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Tutor>>;
    public getTutorPerId(idTutor: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Tutor>>;
    public getTutorPerId(idTutor: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idTutor === null || idTutor === undefined) {
            throw new Error('Required parameter idTutor was null or undefined when calling getTutorPerId.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idTutor !== undefined && idTutor !== null) {
            queryParameters = queryParameters.set('idTutor', <any>idTutor);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Tutor>('get',`${this.basePath}/tutor`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * disassocia un tutor dall&#x27;idea di impresa
     * disassocia il tutor dall&#x27;idea di impresa ed invia mail al soggetto attuatore
     * @param idIdeaImpresa 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public resetTutor(idIdeaImpresa: number, observe?: 'body', reportProgress?: boolean): Observable<IdeaDiImpresa>;
    public resetTutor(idIdeaImpresa: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IdeaDiImpresa>>;
    public resetTutor(idIdeaImpresa: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IdeaDiImpresa>>;
    public resetTutor(idIdeaImpresa: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idIdeaImpresa === null || idIdeaImpresa === undefined) {
            throw new Error('Required parameter idIdeaImpresa was null or undefined when calling resetTutor.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idIdeaImpresa !== undefined && idIdeaImpresa !== null) {
            queryParameters = queryParameters.set('idIdeaImpresa', <any>idIdeaImpresa);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IdeaDiImpresa>('delete',`${this.basePath}/tutor/reset-tutor`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * aggiunge il tutor all&#x27;idea di impresa
     * aggiunge il tutor all&#x27;idea di impresa ed invia mail al cittadino e soggetto attuatore
     * @param idTutor id cittadino a collegare con l&#x27;idea di impresa
     * @param idImpresa id cittadino a collegare con l&#x27;idea di impresa
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sceltaTutor(idTutor: number, idImpresa: number, observe?: 'body', reportProgress?: boolean): Observable<IdeaDiImpresa>;
    public sceltaTutor(idTutor: number, idImpresa: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IdeaDiImpresa>>;
    public sceltaTutor(idTutor: number, idImpresa: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IdeaDiImpresa>>;
    public sceltaTutor(idTutor: number, idImpresa: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (idTutor === null || idTutor === undefined) {
            throw new Error('Required parameter idTutor was null or undefined when calling sceltaTutor.');
        }

        if (idImpresa === null || idImpresa === undefined) {
            throw new Error('Required parameter idImpresa was null or undefined when calling sceltaTutor.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idTutor !== undefined && idTutor !== null) {
            queryParameters = queryParameters.set('idTutor', <any>idTutor);
        }
        if (idImpresa !== undefined && idImpresa !== null) {
            queryParameters = queryParameters.set('idImpresa', <any>idImpresa);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IdeaDiImpresa>('put',`${this.basePath}/tutor/scelta-tutor`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
