/**
 * @license
 *
 * Copyright © 2025 Regione Piemonte
 *
 * Licensed under the EUPL, Version 1.2 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 *
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 * https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 * or
 * https://opensource.org/license/EUPL-1.2
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */

/**
 * API mipcommonapi
 * API comuni mipcittadino e mipbackoffice
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Cittadinanza } from './cittadinanza';
import { Cittadino } from './cittadino';
import { Comune } from './comune';
import { CondizioneFamiliare } from './condizioneFamiliare';
import { CondizioneOccupazionale } from './condizioneOccupazionale';
import { StatoEstero } from './statoEstero';
import { SvantaggioAbitativo } from './svantaggioAbitativo';
import { TitoloDiStudio } from './titoloDiStudio';

export interface AnagraficaCittadino { 
    id?: number;
    cittadino?: Cittadino;
    dataNascita?: Date;
    comuneNascita?: Comune;
    numeroDocumentoIdentita?: string;
    documentoRilasciatoDa?: string;
    dataScadenzaDocumento?: Date;
    statoEsteroNascita?: StatoEstero;
    descrizioneCittaEsteraNascita?: string;
    codiceCittadinanza?: Cittadinanza;
    descCittadinanzaAltro?: string;
    comuneResidenza?: Comune;
    codiceStatoEsteroResidenza?: number;
    descrizioneCittaEsteraResidenza?: string;
    indirizzoResidenza?: string;
    capResidenza?: string;
    comuneDomicilio?: Comune;
    indirizzoDomicilio?: string;
    capDomicilio?: string;
    recapitoEmail?: string;
    recapitoEmail2?: string;
    recapitoTelefono?: string;
    recapitoTelefono2?: string;
    numeroPermessoDiSoggiorno?: string;
    descrMotivoPermessoDiSoggiorno?: string;
    permessoDiSoggiornoRilasciatoDa?: string;
    dataScadPermessoSoggiorno?: Date;
    tipoPermessoDiSoggiorno?: string;
    condizioneOccupazionaleAltro?: string;
    codiceTitoloDiStudio?: TitoloDiStudio;
    titoloDiStudioAltro?: string;
    codiceCondizioneOccupazionale?: CondizioneOccupazionale;
    svantaggioAbitativo?: SvantaggioAbitativo;
    condizioneFamiliare?: CondizioneFamiliare;
    sesso?: string;
    flgIdeaImpresa?: boolean;
    codUserInserim?: string;
    dataInserim?: Date;
    codUserAggiorn?: string;
    dataAggiorn?: Date;
}